### ISSUE TITLE
Tests are failing under a different timezone

### ISSUE THREAD

**Issue by sanmai** [hughgrigg/php-business-time#40]
It could be an actual bug, but I think it just the tests are fragile.

For example:
```
There were 18 failures:

1) BusinessTime\Tests\Unit\BusinessTime\RoundTest::testFloor with data set #6 ('2018-05-23 17:23', BusinessTime\Interval Object (...), '2018-05-23 16:00')
2018-05-23 17:23 floored to 2 hours should be 2018-05-23 16:00; got 2018-05-23 17:00.
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'2018-05-23 16:00'
+'2018-05-23 17:00'

...

18) BusinessTime\Tests\Unit\BusinessTime\RoundTest::testCeil with data set #12 ('2018-05-23 17:23', BusinessTime\Interval Object (...), '2018-05-24 00:00')
Ceil of 2018-05-23 17:23 to 1 day should be 2018-05-24 00:00; got 2018-05-24 09:00.
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-'2018-05-24 00:00'
+'2018-05-24 09:00'
```

This last line made me suspicious 'cause I'm actually testing this now in UTC+9 (JST).

**Comment by hughgrigg** [comment]
Classic. I'll take a look, should be easy to fix.

**Comment by hughgrigg** [comment]
@sanmai I've put this in to add some tests for different timezones: https://github.com/hughgrigg/php-business-time/pull/42

In doing so I found a separate bug which is described there; that PR should fix it.

For this one, I think you are right that it is flaky tests as opposed to a bug. I'm trying to find a way to reproduce it.

**Comment by hughgrigg** [comment]
I think the cause of these tests being flaky also causes a lot of other tests to be flaky. Sometimes the time is off by e.g. ~1 minute. Still trying to track it down.

**Comment by hughgrigg** [comment]
Resolved.
