### ISSUE TITLE
addBusinessDay() returns non-business day if time part is before startOfBusinessDay()

### ISSUE THREAD

**Issue by bzoks** [hughgrigg/php-business-time#45]
Sample from docs:
```php
$friday = new BusinessTime\BusinessTime('Friday');
$nextBusinessDay = $friday->addBusinessDay();
// = Monday
```
actually returns Saturday:
```php
print $friday->format("r"); 
// = Fri, 01 Mar 2019 00:00:00 +0100
print $nextBusinessDay->format("r"); 
// = Sat, 02 Mar 2019 00:00:00 +0100
```
I figured out that this happens if time part is less than startOfBusinessDay(), so result is correct if time is (by defaut) 10:00 or more:
```php
$friday = new \BusinessTime\BusinessTime('Friday 10:00');
// Fri, 01 Mar 2019 10:00:00 +0100
print $nextBusinessDay->format("r"); 
// = Mon, 04 Mar 2019 10:00:00 +0100
```
I was trying to overcome this by setting precision to day etc., but for now without success.

**Comment by hughgrigg** [comment]
If the start time is before the start of the business day, then a whole business day has passed, hence it moving ahead this much. I'd suggest using `startOfBusinessDay()` first if you want to avoid this. The docs could make this clearer with the start time, though.

**Comment by bzoks** [comment]
In my use case I'm not using time part at all, just days. I do not expect to ever get non-business day from this function.

**Comment by hughgrigg** [comment]
Hmm, this is quite tricky. I agree that `Friday 1am -> Saturday 1am` is not natural. Going to `Monday 1am` also seems somewhat arbitrary, though.

Instead of working through in units of the precision, it could move forward in whole days and stop when adding another day would elapse more than the amount of business days. Then `Friday 1am` would skip to `Monday 1am` with the default settings. The difficulty with that is when you configure irregular business time constraints, e.g. half days on Wednesdays, it will not reflect that naturally.

An alternative could be to have a `BusinessDate` class that is only concerned with whole days. The logic would be different and simpler, and might serve your use case better?

By the way, it sounds like Carbon's `addWeekdays()` method might actually cover your needs if you're using the default Mon-Fri.

**Comment by bzoks** [comment]
I had to continue with my project, so I switched to cmixin/business-day, which upgrades Carbon with my requirements (custom holidays, for example during collective holiday in company). It works on day-precision only, as would your proposed BusinessDate.
When I'll need hour-precision, I'll try to use your library again, so I do care that it gets fixes/improved.

Regarding irregular business time constraints:
for my understanding, it would be expected that adding one work day could mean adding 8 hours (if such duration is configured) to current hour (instead 24 hours), but adding those hours during working time. So if initial time is 1am and I add 8 working hours, and working day starts at 10am, I would expect that result is 10am+8h=6pm or just after end of working day, so actually on start of next business day (to me it doesn't matter if start of day (0am) or start of businesstime (10am).... as long as it is working day, not Saturday, as currently.
But for more claritiy, adding working day should be different than adding working time of full working day... that is - different function calls: one would add whole day (24 hours), and one would add 8 hours... both would result in next working day, so never on Saturday (except if it is configured to be working day).

Best regards,
  Boštjan

**Comment by hughgrigg** [comment]
Yes, you're right that the confusion comes down to whether a business day is e.g. 8 hours, or 24 hours which includes business time. Currently this library treats it as 8 hours. Even then, going to 6pm would also be wrong -- the hour between 5pm and 6pm is not business time, so it should not be counted.

I'm going to have a think about the best way to make these options available clearly and intuitively. People assume different things about what "business day" means, so it would be good to have a clear separation for these use cases.

By the way, you can have custom holidays with this library (which I need for my use cases), e.g. by adding a `DatesOfYear()` constraint, or whichever constraint makes it easiest. You can also implement the `BusinessTimeConstraint` interface to e.g. pull dates from a database.

**Comment by bzoks** [comment]
I know I can use custom holidays with this library, I used that feature. But since I am working with full-days only (time part always 0:00), adding 1 business day and getting non-working day was showstopper for me.

**Comment by hughgrigg** [comment]
I understand. I'll have a think about the best way to present a nice API for this as it would be good to make either approach easy to use.

**Comment by hughgrigg** [comment]
@bzoks I think the best solution could be to ensure that `addBusinessDays()` and `subtractBusinessDays()` always end on a business day, as you said. A business day would be defined as a day containing any amount of business time.

**Comment by hughgrigg** [comment]
@bzoks I think it is actually fine to solve this by always having the day methods on a business day, as you suggest: https://github.com/hughgrigg/php-business-time/pull/48
