### ISSUE TITLE
Add support for carbon ^2.0

### ISSUE THREAD

**Issue by efillman** [hughgrigg/php-business-time#46]
Do you know if the library might be inherently compatible with carbon ^2.0? I am getting a dependency clobber on having carbon 2.18 installed for another package.

composer.json
```
"require": {
        "php": "^7.0",
        "nesbot/carbon": "^1.25"
    },


Suggested Fix:
"require": {
        "php": "^7.0",
        "nesbot/carbon": "^1.25 || ^2.0"
    },
```

**Comment by hughgrigg** [comment]
https://github.com/hughgrigg/php-business-time/pull/50
