### ISSUE TITLE
2.1 not in packagist?

### ISSUE THREAD

**Issue by Synchro** [hughgrigg/php-business-time#52]
I see you committed and tagged 2.1.0 with Carbon 2 support (thank you!), but it seems it's not been picked up by packagist, so composer doesn't see it either - could you give it a kick please? It could be that the master branch has not had a successful build since the 2.1 merge.

**Comment by hughgrigg** [comment]
@Synchro 2.1.1 is now available in Packagist. For some reason it doesn't want to pick up 2.1.0

https://packagist.org/packages/hughgrigg/php-business-time#2.1.1

Thanks for pointing this out, and sorry for the delay in fixing it.

**Comment by Synchro** [comment]
Thanks for doing that.
